// <auto-generated />
namespace API.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CommentDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201911030016126_CommentDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
