// <auto-generated />
namespace API.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(description));
        
        string IMigrationMetadata.Id
        {
            get { return "201912150000012_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
